"use client";

import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Menu, X } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <html lang="en">
      <head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-white shadow-md fixed w-full top-0 z-50">
          <div className="container mx-auto flex items-center justify-between py-4 px-6">
            <h1 className="text-xl font-bold text-blue-600">Career Compass</h1>
            
            {/* Mobile Menu Button */}
            <button
              className="md:hidden text-gray-700"
              onClick={() => setMenuOpen(!menuOpen)}
            >
              {menuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
            
            {/* Navigation Links */}
            <nav className={`md:flex space-x-6 ${menuOpen ? "block" : "hidden"} md:block absolute md:relative top-full left-0 w-full md:w-auto bg-white md:bg-transparent p-6 md:p-0 shadow-md md:shadow-none`}>
              <Link href="/" className="block md:inline text-gray-700 hover:text-blue-500 py-2">Home</Link>
              <Link href="/career" className="block md:inline text-gray-700 hover:text-blue-500 py-2">Careers</Link>
              <Link href="/resource" className="block md:inline text-gray-700 hover:text-blue-500 py-2">Resources</Link>
              <Link href="/about" className="block md:inline text-gray-700 hover:text-blue-500 py-2">About</Link>
              <Link href="/contact" className="block md:inline text-gray-700 hover:text-blue-500 py-2">Contact</Link>
            </nav>
          </div>
        </header>
        
        {/* Main Content */}
        <main className="mt-16">{children}</main>
        
        {/* Footer */}
        <footer className="bg-blue-800 text-white py-8 mt-12">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 text-center md:text-left">
            <div>
              <h5 className="font-semibold mb-4">Career Compass</h5>
              <p>&copy; 2026 CareerCompass. All Rights Reserved.</p>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Quick Links</h5>
              <ul>
                <li><Link href="/" className="hover:underline">Home</Link></li>
                <li><Link href="/services" className="hover:underline">Services</Link></li>
                <li><Link href="/contact" className="hover:underline">Contact</Link></li>
              </ul>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Support</h5>
              <ul>
                <li><Link href="/contact" className="hover:underline">FAQs</Link></li>
                <li><Link href="/contact" className="hover:underline">Privacy Policy</Link></li>
                <li><Link href="/contact" className="hover:underline">Terms of Service</Link></li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
