// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-md">
          <div className="container mx-auto flex items-center justify-between py-4 px-6">
            <h1 className="text-xl font-bold text-blue-600">Career Compass</h1>
            <nav className="flex space-x-6">
              <a href="/" className="text-gray-700 hover:text-blue-500">
                Home
              </a>
              <a href="/career" className="text-gray-700 hover:text-blue-500">
                Careers
              </a>
              <a href="/resource" className="text-gray-700 hover:text-blue-500">
                Resources
              </a>
              <a href="/about" className="text-gray-700 hover:text-blue-500">
                About
              </a>
              <a href="/contact" className="text-gray-700 hover:text-blue-500">
                Contact
              </a>
              {/* <SignedOut>
                  <p className="text-gray-700 hover:text-blue-500">
                    <SignInButton mode="modal" />
                  </p>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn> */}
            </nav>
          </div>
        </header>

        {children}
        {/* Footer Section */}
        <footer className="bg-blue-800 text-white py-8">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h5 className="font-semibold mb-4">Career Compass</h5>
              <p>&copy; 2026 CareerCompass. All Rights Reserved.</p>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Quick Links</h5>
              <ul>
                <li>
                  <a href="/" className="hover:underline">
                    Home
                  </a>
                </li>
                <li>
                  <a href="/" className="hover:underline">
                    Services
                  </a>
                </li>
                <li>
                  <a href="/contact" className="hover:underline">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Support</h5>
              <ul>
                <li>
                  <a href="/contact" className="hover:underline">
                    FAQs
                  </a>
                </li>
                <li>
                  <a href="/contact" className="hover:underline">
                    Privacy Policy
                  </a>
                </li>
                <li>
                  <a href="/contact" className="hover:underline">
                    Terms of Service
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
    // </ClerkProvider>
  );
}
